events { 
    worker_connections 1024; 
}

http {
    upstream backend_api {
        # Вказуємо Nginx, на які контейнери перенаправляти трафік
        server api1:3000;
        server api2:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Прокидаємо заголовки, щоб клієнт бачив X-Instance-ID від бекенду
            proxy_pass_header X-Instance-ID;
        }
    }
}